version: '3'
services:
  btc-node-api:
    build: .
    image: btc-node-api
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - bitcoin-node

  bitcoin-node:
    image: ruimarinho/bitcoin-core
    ports:
      - '8332:8332'
    volumes:
      - bitcoin-data:/data

volumes:
  bitcoin-data:
